"""Añadir campos perfil usuario

Revision ID: 6bdfb7c3271e
Revises: bcb0ebdaff0f
Create Date: 2026-08-26 13:44:55.365933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdfb7c3271e'
down_revision: Union[str, None] = 'bcb0ebdaff0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('intereses', sa.JSON(), nullable=True), schema='usuarios')
    op.add_column('usuario', sa.Column('objetivos', sa.Text(), nullable=True), schema='usuarios')
    op.add_column('usuario', sa.Column('preferencias', sa.JSON(), nullable=True), schema='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'preferencias', schema='usuarios')
    op.drop_column('usuario', 'objetivos', schema='usuarios')
    op.drop_column('usuario', 'intereses', schema='usuarios')
    # ### end Alembic commands ###
