"""Crear tablas del modulo ia

Revision ID: 9d8bf7c9c3e5
Revises: 0660f7ed1be0
Create Date: 2026-08-25 15:51:17.501438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8bf7c9c3e5'
down_revision: Union[str, None] = '0660f7ed1be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rutas_aprendizaje',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('nivel_objetivo', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('generada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ia'
    )
    op.create_table('lecciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ruta_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('contenido', sa.JSON(), nullable=True),
    sa.Column('dificultad', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['ruta_id'], ['ia.rutas_aprendizaje.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ia'
    )
    op.create_table('mensajes_tutor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('leccion_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leccion_id'], ['ia.lecciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='ia'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensajes_tutor', schema='ia')
    op.drop_table('lecciones', schema='ia')
    op.drop_table('rutas_aprendizaje', schema='ia')
    # ### end Alembic commands ###
