"""Crear base de datos completa

Revision ID: bcb0ebdaff0f
Revises: 9d8bf7c9c3e5
Create Date: 2026-08-25 16:54:19.456019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb0ebdaff0f'
down_revision: Union[str, None] = '9d8bf7c9c3e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS progreso')
    op.execute('CREATE SCHEMA IF NOT EXISTS pagos')
    op.execute('CREATE SCHEMA IF NOT EXISTS sesiones')
    op.create_table('logros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('criterio', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='progreso'
    )
    op.create_table('suscripciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pagos'
    )
    op.create_table('transacciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='pagos'
    )
    op.create_table('logros_usuario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('logro_id', sa.UUID(), nullable=False),
    sa.Column('obtenido_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['logro_id'], ['progreso.logros.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='progreso'
    )
    op.create_table('rachas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('dias_actuales', sa.Integer(), nullable=False),
    sa.Column('mejor_racha', sa.Integer(), nullable=False),
    sa.Column('ultima_actividad', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='progreso'
    )
    op.create_table('xp_historial',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='progreso'
    )
    op.create_table('sesiones_estudio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creador_id', sa.UUID(), nullable=False),
    sa.Column('codigo_invitacion', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_invitacion'),
    schema='sesiones'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='usuarios'
    )
    op.create_table('mensajes_sesion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.sesiones_estudio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sesiones'
    )
    op.create_table('participantes_sesion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('conectado', sa.Boolean(), nullable=False),
    sa.Column('unido_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones.sesiones_estudio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sesiones'
    )
    op.create_table('progreso_leccion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('leccion_id', sa.UUID(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.Column('puntaje', sa.Integer(), nullable=False),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leccion_id'], ['ia.lecciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='progreso'
    )
    op.add_column('usuario', sa.Column('nivel', sa.String(length=50), nullable=True), schema='usuarios')
    op.add_column('usuario', sa.Column('plan', sa.String(length=50), nullable=True), schema='usuarios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'plan', schema='usuarios')
    op.drop_column('usuario', 'nivel', schema='usuarios')
    op.drop_table('progreso_leccion', schema='progreso')
    op.drop_table('participantes_sesion', schema='sesiones')
    op.drop_table('mensajes_sesion', schema='sesiones')
    op.drop_table('refresh_tokens', schema='usuarios')
    op.drop_table('sesiones_estudio', schema='sesiones')
    op.drop_table('xp_historial', schema='progreso')
    op.drop_table('rachas', schema='progreso')
    op.drop_table('logros_usuario', schema='progreso')
    op.drop_table('transacciones', schema='pagos')
    op.drop_table('suscripciones', schema='pagos')
    op.drop_table('logros', schema='progreso')
    # ### end Alembic commands ###
